# 应用服务 WEB 访问端口
server:
  port: 8082

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#webdav:
  #base-url: "http://47.97.38.187:5005"
  #base-path: "/home/cesc"
  #username: "18360937126"
  #password: "Qwq781018"


mybatis:
  # 搜索指定包别名
  typeAliasesPackage: tcdx.uap.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: true
      write-null-map-values: false
    default-property-inclusion: non_null
  datasource:
    # url: jdbc:postgresql://192.168.100.1:5432/flowable-learn?reWriteBatchedInserts=true
    # username: postgres
    # password: pgsql
    url: jdbc:postgresql://49.72.46.57:5432/backupclean?reWriteBatchedInserts=true&serverTimezone=Asia/Shanghai
    username: postgres
    password: wenqiang24!
    #url: jdbc:postgresql://localhost:5432/low-code?reWriteBatchedInserts=true&serverTimezone=Asia/Shanghai
    #username: postgres
    #password: postgres
    hikari:
      auto-commit: true
      connection-test-query: select 1
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 180000  # 空闲连接超时时间3分钟
      max-lifetime: 300000
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

logging:
  level:
    org.flowable: DEBUG
    mybatis: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

liteflow:
#  rule-source: liteflow/liteflow.xml
  rule-source-ext-data-map:
#    driverClassName: com.mysql.cj.jdbc.Driver
    applicationName: new-uap
    #是否开启SQL日志
    sqlLogEnabled: true
    #是否开启SQL数据轮询自动刷新机制 默认不开启
    pollingEnabled: true
    pollingIntervalSeconds: 60
    pollingStartSeconds: 60
    #以下是chain表的配置，这个一定得有
    chainTableName: liteflow_chain
    chainApplicationNameField: application_name
    chainNameField: chain_name
    elDataField: el_data
    #以下是决策路由字段的配置，如果你没用到决策路由，可以不配置
#    routeField: route
#    namespaceField: namespace
    #是否启用这条规则
    chainEnableField: enable
    #规则表自定义过滤SQL
#    chainCustomSql:
    #以下是script表的配置，如果你没使用到脚本，下面可以不配置
    scriptTableName: liteflow_script
    scriptApplicationNameField: application_name
    scriptIdField: script_id
    scriptNameField: script_name
    scriptDataField: script_data
    scriptTypeField: script_type
    scriptLanguageField: script_language
    #是否启用这条脚本
    scriptEnableField: enable
    #脚本表自定义过滤SQL
#    scriptCustomSql: